package com.bear.bearlibrary.model.po;

import java.time.LocalDateTime;

public class InvitationCodePo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invitation_code.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invitation_code.administrator_id
     *
     * @mbg.generated
     */
    private Long administratorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invitation_code.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invitation_code.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invitation_code.valid_time
     *
     * @mbg.generated
     */
    private LocalDateTime validTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invitation_code.id
     *
     * @return the value of invitation_code.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invitation_code.id
     *
     * @param id the value for invitation_code.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invitation_code.administrator_id
     *
     * @return the value of invitation_code.administrator_id
     *
     * @mbg.generated
     */
    public Long getAdministratorId() {
        return administratorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invitation_code.administrator_id
     *
     * @param administratorId the value for invitation_code.administrator_id
     *
     * @mbg.generated
     */
    public void setAdministratorId(Long administratorId) {
        this.administratorId = administratorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invitation_code.user_id
     *
     * @return the value of invitation_code.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invitation_code.user_id
     *
     * @param userId the value for invitation_code.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invitation_code.code
     *
     * @return the value of invitation_code.code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invitation_code.code
     *
     * @param code the value for invitation_code.code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invitation_code.valid_time
     *
     * @return the value of invitation_code.valid_time
     *
     * @mbg.generated
     */
    public LocalDateTime getValidTime() {
        return validTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invitation_code.valid_time
     *
     * @param validTime the value for invitation_code.valid_time
     *
     * @mbg.generated
     */
    public void setValidTime(LocalDateTime validTime) {
        this.validTime = validTime;
    }
}