package com.bear.bearlibrary.mapper;

import com.bear.bearlibrary.model.po.AdministratorPo;
import com.bear.bearlibrary.model.po.AdministratorPoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AdministratorPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrator
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrator
     *
     * @mbg.generated
     */
    int insert(AdministratorPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrator
     *
     * @mbg.generated
     */
    int insertSelective(AdministratorPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrator
     *
     * @mbg.generated
     */
    List<AdministratorPo> selectByExample(AdministratorPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrator
     *
     * @mbg.generated
     */
    AdministratorPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrator
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AdministratorPo record, @Param("example") AdministratorPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrator
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AdministratorPo record, @Param("example") AdministratorPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrator
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AdministratorPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrator
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AdministratorPo record);
}