package com.bear.bearlibrary.mapper;

import com.bear.bearlibrary.model.po.CheckPo;
import com.bear.bearlibrary.model.po.CheckPoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CheckPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check
     *
     * @mbg.generated
     */
    int insert(CheckPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check
     *
     * @mbg.generated
     */
    int insertSelective(CheckPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check
     *
     * @mbg.generated
     */
    List<CheckPo> selectByExample(CheckPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check
     *
     * @mbg.generated
     */
    CheckPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CheckPo record, @Param("example") CheckPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CheckPo record, @Param("example") CheckPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CheckPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CheckPo record);
}