package com.bear.bearlibrary.mapper;

import com.bear.bearlibrary.model.po.ContributionPo;
import com.bear.bearlibrary.model.po.ContributionPoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ContributionPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contribution
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contribution
     *
     * @mbg.generated
     */
    int insert(ContributionPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contribution
     *
     * @mbg.generated
     */
    int insertSelective(ContributionPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contribution
     *
     * @mbg.generated
     */
    List<ContributionPo> selectByExample(ContributionPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contribution
     *
     * @mbg.generated
     */
    ContributionPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contribution
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ContributionPo record, @Param("example") ContributionPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contribution
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ContributionPo record, @Param("example") ContributionPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contribution
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ContributionPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contribution
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ContributionPo record);
}