package com.bear.bearlibrary.mapper;

import com.bear.bearlibrary.model.po.InvitationCodePo;
import com.bear.bearlibrary.model.po.InvitationCodePoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InvitationCodePoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invitation_code
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invitation_code
     *
     * @mbg.generated
     */
    int insert(InvitationCodePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invitation_code
     *
     * @mbg.generated
     */
    int insertSelective(InvitationCodePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invitation_code
     *
     * @mbg.generated
     */
    List<InvitationCodePo> selectByExample(InvitationCodePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invitation_code
     *
     * @mbg.generated
     */
    InvitationCodePo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invitation_code
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") InvitationCodePo record, @Param("example") InvitationCodePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invitation_code
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") InvitationCodePo record, @Param("example") InvitationCodePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invitation_code
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(InvitationCodePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invitation_code
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(InvitationCodePo record);
}