package com.bear.bearlibrary.mapper;

import com.bear.bearlibrary.model.po.PicturePo;
import com.bear.bearlibrary.model.po.PicturePoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PicturePoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picture
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picture
     *
     * @mbg.generated
     */
    int insert(PicturePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picture
     *
     * @mbg.generated
     */
    int insertSelective(PicturePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picture
     *
     * @mbg.generated
     */
    List<PicturePo> selectByExample(PicturePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picture
     *
     * @mbg.generated
     */
    PicturePo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picture
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PicturePo record, @Param("example") PicturePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picture
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PicturePo record, @Param("example") PicturePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picture
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PicturePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picture
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PicturePo record);
}