package com.bear.service.model.po;

import java.time.LocalDateTime;

public class CheckPo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check.administrator_id
     *
     * @mbg.generated
     */
    private Long administratorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check.url
     *
     * @mbg.generated
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check.point
     *
     * @mbg.generated
     */
    private Long point;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check.exp
     *
     * @mbg.generated
     */
    private Long exp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check.comment
     *
     * @mbg.generated
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check.gmt_create
     *
     * @mbg.generated
     */
    private LocalDateTime gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check.gmt_modified
     *
     * @mbg.generated
     */
    private LocalDateTime gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check.create_id
     *
     * @mbg.generated
     */
    private Long createId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check.create_name
     *
     * @mbg.generated
     */
    private String createName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check.modified_id
     *
     * @mbg.generated
     */
    private Long modifiedId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check.modified_name
     *
     * @mbg.generated
     */
    private String modifiedName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check.id
     *
     * @return the value of check.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check.id
     *
     * @param id the value for check.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check.user_id
     *
     * @return the value of check.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check.user_id
     *
     * @param userId the value for check.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check.administrator_id
     *
     * @return the value of check.administrator_id
     *
     * @mbg.generated
     */
    public Long getAdministratorId() {
        return administratorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check.administrator_id
     *
     * @param administratorId the value for check.administrator_id
     *
     * @mbg.generated
     */
    public void setAdministratorId(Long administratorId) {
        this.administratorId = administratorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check.type
     *
     * @return the value of check.type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check.type
     *
     * @param type the value for check.type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check.url
     *
     * @return the value of check.url
     *
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check.url
     *
     * @param url the value for check.url
     *
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check.point
     *
     * @return the value of check.point
     *
     * @mbg.generated
     */
    public Long getPoint() {
        return point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check.point
     *
     * @param point the value for check.point
     *
     * @mbg.generated
     */
    public void setPoint(Long point) {
        this.point = point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check.exp
     *
     * @return the value of check.exp
     *
     * @mbg.generated
     */
    public Long getExp() {
        return exp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check.exp
     *
     * @param exp the value for check.exp
     *
     * @mbg.generated
     */
    public void setExp(Long exp) {
        this.exp = exp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check.comment
     *
     * @return the value of check.comment
     *
     * @mbg.generated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check.comment
     *
     * @param comment the value for check.comment
     *
     * @mbg.generated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check.gmt_create
     *
     * @return the value of check.gmt_create
     *
     * @mbg.generated
     */
    public LocalDateTime getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check.gmt_create
     *
     * @param gmtCreate the value for check.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(LocalDateTime gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check.gmt_modified
     *
     * @return the value of check.gmt_modified
     *
     * @mbg.generated
     */
    public LocalDateTime getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check.gmt_modified
     *
     * @param gmtModified the value for check.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(LocalDateTime gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check.create_id
     *
     * @return the value of check.create_id
     *
     * @mbg.generated
     */
    public Long getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check.create_id
     *
     * @param createId the value for check.create_id
     *
     * @mbg.generated
     */
    public void setCreateId(Long createId) {
        this.createId = createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check.create_name
     *
     * @return the value of check.create_name
     *
     * @mbg.generated
     */
    public String getCreateName() {
        return createName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check.create_name
     *
     * @param createName the value for check.create_name
     *
     * @mbg.generated
     */
    public void setCreateName(String createName) {
        this.createName = createName == null ? null : createName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check.modified_id
     *
     * @return the value of check.modified_id
     *
     * @mbg.generated
     */
    public Long getModifiedId() {
        return modifiedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check.modified_id
     *
     * @param modifiedId the value for check.modified_id
     *
     * @mbg.generated
     */
    public void setModifiedId(Long modifiedId) {
        this.modifiedId = modifiedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check.modified_name
     *
     * @return the value of check.modified_name
     *
     * @mbg.generated
     */
    public String getModifiedName() {
        return modifiedName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check.modified_name
     *
     * @param modifiedName the value for check.modified_name
     *
     * @mbg.generated
     */
    public void setModifiedName(String modifiedName) {
        this.modifiedName = modifiedName == null ? null : modifiedName.trim();
    }
}