package com.bear.service.model.po;

import java.time.LocalDateTime;

public class InvitationCodePo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invitation_code.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invitation_code.administrator_id
     *
     * @mbg.generated
     */
    private Long administratorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invitation_code.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invitation_code.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invitation_code.valid_time
     *
     * @mbg.generated
     */
    private LocalDateTime validTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invitation_code.gmt_create
     *
     * @mbg.generated
     */
    private LocalDateTime gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invitation_code.gmt_modified
     *
     * @mbg.generated
     */
    private LocalDateTime gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invitation_code.create_id
     *
     * @mbg.generated
     */
    private Long createId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invitation_code.create_name
     *
     * @mbg.generated
     */
    private String createName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invitation_code.modified_id
     *
     * @mbg.generated
     */
    private Long modifiedId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invitation_code.modified_name
     *
     * @mbg.generated
     */
    private String modifiedName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invitation_code.id
     *
     * @return the value of invitation_code.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invitation_code.id
     *
     * @param id the value for invitation_code.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invitation_code.administrator_id
     *
     * @return the value of invitation_code.administrator_id
     *
     * @mbg.generated
     */
    public Long getAdministratorId() {
        return administratorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invitation_code.administrator_id
     *
     * @param administratorId the value for invitation_code.administrator_id
     *
     * @mbg.generated
     */
    public void setAdministratorId(Long administratorId) {
        this.administratorId = administratorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invitation_code.user_id
     *
     * @return the value of invitation_code.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invitation_code.user_id
     *
     * @param userId the value for invitation_code.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invitation_code.code
     *
     * @return the value of invitation_code.code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invitation_code.code
     *
     * @param code the value for invitation_code.code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invitation_code.valid_time
     *
     * @return the value of invitation_code.valid_time
     *
     * @mbg.generated
     */
    public LocalDateTime getValidTime() {
        return validTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invitation_code.valid_time
     *
     * @param validTime the value for invitation_code.valid_time
     *
     * @mbg.generated
     */
    public void setValidTime(LocalDateTime validTime) {
        this.validTime = validTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invitation_code.gmt_create
     *
     * @return the value of invitation_code.gmt_create
     *
     * @mbg.generated
     */
    public LocalDateTime getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invitation_code.gmt_create
     *
     * @param gmtCreate the value for invitation_code.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(LocalDateTime gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invitation_code.gmt_modified
     *
     * @return the value of invitation_code.gmt_modified
     *
     * @mbg.generated
     */
    public LocalDateTime getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invitation_code.gmt_modified
     *
     * @param gmtModified the value for invitation_code.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(LocalDateTime gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invitation_code.create_id
     *
     * @return the value of invitation_code.create_id
     *
     * @mbg.generated
     */
    public Long getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invitation_code.create_id
     *
     * @param createId the value for invitation_code.create_id
     *
     * @mbg.generated
     */
    public void setCreateId(Long createId) {
        this.createId = createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invitation_code.create_name
     *
     * @return the value of invitation_code.create_name
     *
     * @mbg.generated
     */
    public String getCreateName() {
        return createName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invitation_code.create_name
     *
     * @param createName the value for invitation_code.create_name
     *
     * @mbg.generated
     */
    public void setCreateName(String createName) {
        this.createName = createName == null ? null : createName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invitation_code.modified_id
     *
     * @return the value of invitation_code.modified_id
     *
     * @mbg.generated
     */
    public Long getModifiedId() {
        return modifiedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invitation_code.modified_id
     *
     * @param modifiedId the value for invitation_code.modified_id
     *
     * @mbg.generated
     */
    public void setModifiedId(Long modifiedId) {
        this.modifiedId = modifiedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invitation_code.modified_name
     *
     * @return the value of invitation_code.modified_name
     *
     * @mbg.generated
     */
    public String getModifiedName() {
        return modifiedName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invitation_code.modified_name
     *
     * @param modifiedName the value for invitation_code.modified_name
     *
     * @mbg.generated
     */
    public void setModifiedName(String modifiedName) {
        this.modifiedName = modifiedName == null ? null : modifiedName.trim();
    }
}