package com.bear.service.mapper;

import com.bear.service.model.po.InvitationCodePo;
import com.bear.service.model.po.InvitationCodePoExample;
import java.util.List;

public interface InvitationCodePoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invitation_code
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invitation_code
     *
     * @mbg.generated
     */
    int insert(InvitationCodePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invitation_code
     *
     * @mbg.generated
     */
    int insertSelective(InvitationCodePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invitation_code
     *
     * @mbg.generated
     */
    List<InvitationCodePo> selectByExample(InvitationCodePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invitation_code
     *
     * @mbg.generated
     */
    InvitationCodePo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invitation_code
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(InvitationCodePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invitation_code
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(InvitationCodePo record);
}